name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initial Setup
      run: |
        ./scripts/setup_ubuntu.bash
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Python Test
      run: python -m pytest
