#!/bin/bash
# Main reference: https://github.com/RobotLocomotion/drake-external-examples/blob/main/scripts/setup/linux/ubuntu/jammy/install_prereqs
# Removed some unused dependencies

set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install --no-install-recommends -y $(cat <<EOF
  ca-certificates
  wget
  gnupg
  cmake
  lsb-release
  python3-pip
  python3-venv
  locale
EOF
)

wget -qO- https://drake-apt.csail.mit.edu/drake.asc | gpg --dearmor - \
  | tee /etc/apt/trusted.gpg.d/drake.gpg >/dev/null


echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/$(lsb_release -cs) $(lsb_release -cs) main" \
  | tee /etc/apt/sources.list.d/drake.list >/dev/null

apt-get update
apt-get install --no-install-recommends -y drake-dev

export PATH="/opt/drake/bin${PATH:+:${PATH}}"
export PYTHONPATH="/opt/drake/lib/python$(python3 -c 'import sys; print("{0}.{1}".format(*sys.version_info))')/site-packages${PYTHONPATH:+:${PYTHONPATH}}"

locale-gen en_US.UTF-8

# Install pybind11 globally
pip3 install pybind11[global]
