#!/bin/bash
# Adapted from https://github.com/RobotLocomotion/drake-external-examples/blob/main/scripts/setup/linux/ubuntu/jammy/install_prereqs

set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
apt install apt
apt-get update
apt-get install --no-install-recommends -y $(cat <<EOF
  ca-certificates
  build-essential
  wget
  gnupg
  cmake
  lsb-release
  python3-dev
  locales
EOF
)

wget -qO- https://drake-apt.csail.mit.edu/drake.asc | gpg --dearmor - \
  | tee /etc/apt/trusted.gpg.d/drake.gpg >/dev/null


echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/$(lsb_release -cs) $(lsb_release -cs) main" \
  | tee /etc/apt/sources.list.d/drake.list >/dev/null

apt-get update
apt-get install --no-install-recommends -y drake-dev

export PATH="/opt/drake/bin${PATH:+:${PATH}}"
export PYTHONPATH="/opt/drake/lib/python$(python3 -c 'import sys; print("{0}.{1}".format(*sys.version_info))')/site-packages${PYTHONPATH:+:${PYTHONPATH}}"
export LD_LIBRARY_PATH="/opt/drake/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

locale-gen en_US.UTF-8
