name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Initial Setup
      run: sudo bash ./scripts/setup_ubuntu

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build and Install
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip3 install nanobind
        python3 -m pip3 install pytest
        python3 -m pip3 install --verbose .

    - name: Test
      run: python -m pytest
