name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Initial Setup
      run: sudo bash ./scripts/setup_ubuntu

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and Install
      run: |
        python3 -m pip install pybind11[global]
        python3 -m pip install pytest
        python3 -m pip install numpy
        python3 -m pip install --verbose .[test]

    - name: Test
      run: |
        export PATH="/opt/drake/bin${PATH:+:${PATH}}"
        export PYTHONPATH="/opt/drake/lib/python$(python3 -c 'import sys; print("{0}.{1}".format(*sys.version_info))')/site-packages${PYTHONPATH:+:${PYTHONPATH}}"
        export LD_LIBRARY_PATH="/opt/drake/lib:$LD_LIBRARY_PATH"
        py.test
