name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Initial Setup
      run: sudo bash ./scripts/setup_ubuntu

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and Install
      run: |
        pip3 install pybind11[global]
        pip3 install pytest
        pip3 install --verbose .[test]

    - name: Test
      run: |
        py.test
