name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    steps:
    - uses: actions/checkout@v4
    - name: Make setup script executable
      run: chmod +x ./scripts/setup_ubuntu

    - name: Initial Setup
      run: ./scripts/setup_ubuntu
      shell: bash

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
      shell: bash

  test:
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
    - name: Run tests
      run: pytest
