name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Initial Setup
      run: sudo bash ./scripts/setup_ubuntu

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and Install
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install pybind11
        python3 -m pip install pytest
        python3 -m pip install numpy
        python3 -m pip install --verbose .

    - name: Test
      run: |
        source .venv/bin/activate
        export LD_LIBRARY_PATH="/opt/drake/lib:$LD_LIBRARY_PATH"
        python3 -m pytest
