name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    steps:
    - uses: actions/checkout@v4
    - name: Make setup script executable
      run: chmod +x ./scripts/setup_ubuntu

    - name: Initial Setup
      run: ./scripts/setup_ubuntu
      shell: bash

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Python Test
      run: |
        # Make a virtualenv
        python3 -m venv .env
        source .env/bin/activate
        pip3 install .
        pip3 install pytest
        python3 -m pytest
