name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initial Setup
      run: |
        sudo ./scripts/setup_ubuntu.bash
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Python Test
      run: |
        # Make a virtualenv
        python3 -m venv .env
        source .env/bin/activate
        pip install .
        py.test
