name: Build Wheels

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build_wheels:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Initial Setup
      run: sudo bash ./scripts/setup_ubuntu

    - name: Install cibuildwheel
      run: pip3 install cibuildwheel==2.17.0

    - name: Build wheels
      run: |
        export PATH="/opt/drake/bin${PATH:+:${PATH}}"
        export PYTHONPATH="/opt/drake/lib/python$(python3 -c 'import sys; print("{0}.{1}".format(*sys.version_info))')/site-packages${PYTHONPATH:+:${PYTHONPATH}}"
        export LD_LIBRARY_PATH="/opt/drake/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
        python3 -m cibuildwheel --output-dir wheelhouse
      # to supply options, put them in 'env', like:
      # env:
      #   CIBW_SOME_OPTION: value

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-jammy_py310
        path: wheelhouse/*.whl
